{
  description = "scripts";

  # This flake.nix was generated by remote-dev init.
  # It defines the remote development environment using Nix.
  #
  # To customize:
  #   1. Top level: declare Nix pull-side cache policy in nixConfig and package sources in inputs
  #   2. Middle layer: extend shared packages or shell helpers
  #   3. Bottom layer: add optional targets such as extra devShells or packages
  #   4. Use the configure-profile skill or your AI assistant for complex changes
  #
  # Keep these comments as a quick customization guide for future edits.

  # Recommended for stable cache hits:
  #   1. Commit flake.lock so Nix inputs stay pinned across machines.
  #   2. Point nixConfig at a regional cache near the remote machine.
  #   3. Push .#dev-cargo-deps and any shells you want cold-start pulls to hit.
  #
  # nixConfig = {
  #   extra-substituters = [
  #     "https://my-region-cache.example.com"
  #   ];
  #   extra-trusted-public-keys = [
  #     "my-region-cache.example.com-1:YOUR_PUBLIC_KEY="
  #   ];
  # };
  #
  # Managed hosts can also prefer the same cache in machine-level nix.conf:
  #   substituters = https://my-region-cache.example.com https://cache.nixos.org/

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
    rust-overlay = {
      url = "github:oxalica/rust-overlay";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    crane = {
      url = "github:ipetkov/crane";
    };
    nixpkgs-claude.url = "github:NixOS/nixpkgs/master";
    nixpkgs-copilot.url = "github:NixOS/nixpkgs/master";
  };

  outputs = { self, nixpkgs, flake-utils, rust-overlay, crane, nixpkgs-claude, nixpkgs-copilot }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        # Middle layer: platform policy and reusable building blocks.
        pkgs = import nixpkgs {
          inherit system;
          overlays = [ (import rust-overlay) ];
        };
        lib = pkgs.lib;
        nativeBuildInputs = with pkgs; [ pkg-config ];
        buildInputs = with pkgs;
          [ openssl gitMinimal openssh fontconfig freetype libwebp alsa-lib mesa ]
          ++ lib.optionals stdenv.isLinux [ vulkan-loader libxkbcommon wayland libx11 libxcursor libxrandr libxi ]
          ++ lib.optionals stdenv.isDarwin [ libiconv darwin.apple_sdk.frameworks.SystemConfiguration ];
        claudePkgs = import nixpkgs-claude {
          inherit system;
          config.allowUnfreePredicate = pkg:
            let
              name = pkg.pname or (nixpkgs.lib.getName pkg);
            in name == "claude-code" || nixpkgs.lib.hasPrefix "claude-code-" name;
        };
        copilotPkgs = import nixpkgs-copilot {
          inherit system;
          config.allowUnfreePredicate = pkg:
            let
              name = pkg.pname or (nixpkgs.lib.getName pkg);
            in name == "github-copilot-cli" || nixpkgs.lib.hasPrefix "github-copilot-cli-" name;
        };
        aiShellPackages = [
          claudePkgs.claude-code-bin
          pkgs.codex
          copilotPkgs.github-copilot-cli
        ];
        rustToolchain = pkgs.rust-bin.stable.latest.minimal.override {
          extensions = [ "rust-src" "rust-analyzer" "clippy" "rustfmt" ];
        };
        baseShellPackages = [
          rustToolchain
          pkgs.cargo-watch
          pkgs.just
          pkgs.zstd
          pkgs.zsh
          pkgs.starship
          pkgs.zsh-autosuggestions
          pkgs.zsh-history-substring-search
          pkgs.zsh-syntax-highlighting
        ];
        craneLib = (crane.mkLib pkgs).overrideToolchain rustToolchain;
        cleanSrc = craneLib.cleanCargoSource ./.;
        commonArgs = {
          src = cleanSrc;
          inherit nativeBuildInputs buildInputs;
        };
        hasCargoLock = builtins.pathExists ./Cargo.lock;
        cargoVendorDir = if hasCargoLock then craneLib.vendorCargoDeps {
          src = cleanSrc;
        } else null;
        cargoVendorConfig = if hasCargoLock then "${cargoVendorDir}/config.toml" else "";
        mkCargoArtifacts = extraArgs: craneLib.buildDepsOnly (commonArgs // {
          inherit cargoVendorDir;
        } // extraArgs);
        releaseCargoArtifacts = if hasCargoLock then mkCargoArtifacts { } else null;
        devCargoArtifacts = if hasCargoLock then mkCargoArtifacts {
          CARGO_PROFILE = "dev";
          doCheck = false;
          # Keep shell cargo builds fingerprint-compatible with warmup restores.
          doRemapPathPrefix = false;
        } else null;
        mkRemoteDevShell =
          { extraPackages ? [ ]
          }:
          pkgs.mkShell {
            inherit nativeBuildInputs buildInputs;
            packages = baseShellPackages ++ extraPackages;

            shellHook = ''
            export REMOTE_DEV_CARGO_VENDOR_CONFIG="${cargoVendorConfig}"
            export CARGO_HOME="$PWD/.remote-dev/cache/cargo-home"
            export RUSTUP_HOME="$PWD/.remote-dev/cache/rustup-home"
            export CARGO_TARGET_DIR="$PWD/target"
            export CARGO_INCREMENTAL=1
            export PKG_CONFIG_PATH="${pkgs.fontconfig.dev}/lib/pkgconfig:${pkgs.freetype.dev}/lib/pkgconfig:${pkgs.libwebp}/lib/pkgconfig:${pkgs.alsa-lib.dev}/lib/pkgconfig:$PKG_CONFIG_PATH"

            # Create Vulkan ICD file for lavapipe software renderer
            mkdir -p "$PWD/.remote-dev/vulkan"
            cat > "$PWD/.remote-dev/vulkan/lvp_icd.aarch64.json" <<EOF
            {
              "ICD": {
                "api_version": "1.3.268",
                "library_path": "${pkgs.mesa}/lib/libvulkan_lvp.so"
              },
              "file_format_version": "1.0.0"
            }
            EOF
            export VK_ICD_FILENAMES="$PWD/.remote-dev/vulkan/lvp_icd.aarch64.json"
            export LD_LIBRARY_PATH="${pkgs.mesa}/lib:${pkgs.vulkan-loader}/lib:$LD_LIBRARY_PATH"
            export WGPU_BACKEND=vulkan

            mkdir -p "$CARGO_HOME" "$RUSTUP_HOME"
            
            if [ -n "$REMOTE_DEV_CARGO_VENDOR_CONFIG" ]; then
              if [ ! -f "$CARGO_HOME/config.toml" ] || ! grep -q 'vendor-for-remote-dev' "$CARGO_HOME/config.toml" 2>/dev/null; then
                echo '# vendor-for-remote-dev' > "$CARGO_HOME/config.toml"
                cat "$REMOTE_DEV_CARGO_VENDOR_CONFIG" >> "$CARGO_HOME/config.toml"
              fi
            elif grep -q 'vendor-for-remote-dev' "$CARGO_HOME/config.toml" 2>/dev/null; then
              rm -f "$CARGO_HOME/config.toml"
            fi
            
            export SHELL="${pkgs.zsh}/bin/zsh"
            
            # Keep the default remote-dev shell consistent.
            if [ -f "$HOME/.zshrc" ]; then
              sed -i \
                -e "s|@ZSH_AUTOSUGGESTIONS@|${pkgs.zsh-autosuggestions}/share/zsh-autosuggestions/zsh-autosuggestions.zsh|g" \
                -e "s|@ZSH_HISTORY_SUBSTRING_SEARCH@|${pkgs.zsh-history-substring-search}/share/zsh-history-substring-search/zsh-history-substring-search.zsh|g" \
                -e "s|@ZSH_SYNTAX_HIGHLIGHTING@|${pkgs.zsh-syntax-highlighting}/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh|g" \
                "$HOME/.zshrc"
            fi
            export REMOTE_DEV_REPO_ROOT="''${REMOTE_DEV_REPO_ROOT:-$PWD}"
            mkdir -p "$REMOTE_DEV_REPO_ROOT/.remote-dev/bin"
            cat >"$REMOTE_DEV_REPO_ROOT/.remote-dev/bin/claude" <<'EOF'
            #!/bin/sh
            set -eu
            repo_root="''${REMOTE_DEV_REPO_ROOT:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}"
            repo_ref="''${repo_root}#ai-claude"
            exec ${pkgs.nix}/bin/nix run --accept-flake-config --extra-experimental-features "nix-command flakes" --no-write-lock-file "$repo_ref" -- "$@"
            EOF
            chmod +x "$REMOTE_DEV_REPO_ROOT/.remote-dev/bin/claude"
            cat >"$REMOTE_DEV_REPO_ROOT/.remote-dev/bin/codex" <<'EOF'
            #!/bin/sh
            set -eu
            repo_root="''${REMOTE_DEV_REPO_ROOT:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}"
            repo_ref="''${repo_root}#ai-codex"
            exec ${pkgs.nix}/bin/nix run --accept-flake-config --extra-experimental-features "nix-command flakes" --no-write-lock-file "$repo_ref" -- "$@"
            EOF
            chmod +x "$REMOTE_DEV_REPO_ROOT/.remote-dev/bin/codex"
            cat >"$REMOTE_DEV_REPO_ROOT/.remote-dev/bin/copilot" <<'EOF'
            #!/bin/sh
            set -eu
            repo_root="''${REMOTE_DEV_REPO_ROOT:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}"
            repo_ref="''${repo_root}#ai-copilot"
            exec ${pkgs.nix}/bin/nix run --accept-flake-config --extra-experimental-features "nix-command flakes" --no-write-lock-file "$repo_ref" -- "$@"
            EOF
            chmod +x "$REMOTE_DEV_REPO_ROOT/.remote-dev/bin/copilot"
            case ":$PATH:" in
              *":$REMOTE_DEV_REPO_ROOT/.remote-dev/bin:"*) ;;
              *) export PATH="$PATH:$REMOTE_DEV_REPO_ROOT/.remote-dev/bin" ;;
            esac
            '';
          };
      in {
        # Bottom layer: expose concrete targets only.
        packages = pkgs.lib.optionalAttrs hasCargoLock {
          default = craneLib.buildPackage (commonArgs // {
            inherit cargoVendorDir;
            cargoArtifacts = releaseCargoArtifacts;
            pname = "scripts";
            version = "0.1.0";
          });
          dev-cargo-deps = devCargoArtifacts;
        };

        devShells.default = mkRemoteDevShell { };

        # AI shell generated for the configured assistants (Claude Code).
        devShells.with-ai = mkRemoteDevShell {
          extraPackages = aiShellPackages;
        };
        # Optional AI CLI launchers stay isolated from shell activation, so one broken package does not take down the whole remote shell.
        apps = {
          ai-claude = {
            type = "app";
            program = "${claudePkgs.claude-code-bin}/bin/claude";
          };
          ai-codex = {
            type = "app";
            program = "${pkgs.codex}/bin/codex";
          };
          ai-copilot = {
            type = "app";
            program = "${copilotPkgs.github-copilot-cli}/bin/copilot";
          };
        };
    })
  // {
    # Preferred remote-dev shell selector (top-level flake output).
    remoteDev.shell = "with-ai";
  };
}