use ribir_core::prelude::VirtualKeyCode as CVirtualKeyCode;
use winit::event::VirtualKeyCode as WVirtualKeyCode;

pub struct RVirtualKeyCode(WVirtualKeyCode);

impl From<WVirtualKeyCode> for RVirtualKeyCode {
  fn from(value: WVirtualKeyCode) -> Self { RVirtualKeyCode(value) }
}

impl From<RVirtualKeyCode> for WVirtualKeyCode {
  fn from(val: RVirtualKeyCode) -> Self { val.0 }
}

impl From<RVirtualKeyCode> for CVirtualKeyCode {
  fn from(val: RVirtualKeyCode) -> Self {
    match val.0 {
      WVirtualKeyCode::Key1 => CVirtualKeyCode::Key1,
      WVirtualKeyCode::Key2 => CVirtualKeyCode::Key2,
      WVirtualKeyCode::Key3 => CVirtualKeyCode::Key3,
      WVirtualKeyCode::Key4 => CVirtualKeyCode::Key4,
      WVirtualKeyCode::Key5 => CVirtualKeyCode::Key5,
      WVirtualKeyCode::Key6 => CVirtualKeyCode::Key6,
      WVirtualKeyCode::Key7 => CVirtualKeyCode::Key7,
      WVirtualKeyCode::Key8 => CVirtualKeyCode::Key8,
      WVirtualKeyCode::Key9 => CVirtualKeyCode::Key9,
      WVirtualKeyCode::Key0 => CVirtualKeyCode::Key0,

      WVirtualKeyCode::A => CVirtualKeyCode::A,
      WVirtualKeyCode::B => CVirtualKeyCode::B,
      WVirtualKeyCode::C => CVirtualKeyCode::C,
      WVirtualKeyCode::D => CVirtualKeyCode::D,
      WVirtualKeyCode::E => CVirtualKeyCode::E,
      WVirtualKeyCode::F => CVirtualKeyCode::F,
      WVirtualKeyCode::G => CVirtualKeyCode::G,
      WVirtualKeyCode::H => CVirtualKeyCode::H,
      WVirtualKeyCode::I => CVirtualKeyCode::I,
      WVirtualKeyCode::J => CVirtualKeyCode::J,
      WVirtualKeyCode::K => CVirtualKeyCode::K,
      WVirtualKeyCode::L => CVirtualKeyCode::L,
      WVirtualKeyCode::M => CVirtualKeyCode::M,
      WVirtualKeyCode::N => CVirtualKeyCode::N,
      WVirtualKeyCode::O => CVirtualKeyCode::O,
      WVirtualKeyCode::P => CVirtualKeyCode::P,
      WVirtualKeyCode::Q => CVirtualKeyCode::Q,
      WVirtualKeyCode::R => CVirtualKeyCode::R,
      WVirtualKeyCode::S => CVirtualKeyCode::S,
      WVirtualKeyCode::T => CVirtualKeyCode::T,
      WVirtualKeyCode::U => CVirtualKeyCode::U,
      WVirtualKeyCode::V => CVirtualKeyCode::V,
      WVirtualKeyCode::W => CVirtualKeyCode::W,
      WVirtualKeyCode::X => CVirtualKeyCode::X,
      WVirtualKeyCode::Y => CVirtualKeyCode::Y,
      WVirtualKeyCode::Z => CVirtualKeyCode::Z,

      WVirtualKeyCode::Escape => CVirtualKeyCode::Escape,

      WVirtualKeyCode::F1 => CVirtualKeyCode::F1,
      WVirtualKeyCode::F2 => CVirtualKeyCode::F2,
      WVirtualKeyCode::F3 => CVirtualKeyCode::F3,
      WVirtualKeyCode::F4 => CVirtualKeyCode::F4,
      WVirtualKeyCode::F5 => CVirtualKeyCode::F5,
      WVirtualKeyCode::F6 => CVirtualKeyCode::F6,
      WVirtualKeyCode::F7 => CVirtualKeyCode::F7,
      WVirtualKeyCode::F8 => CVirtualKeyCode::F8,
      WVirtualKeyCode::F9 => CVirtualKeyCode::F9,
      WVirtualKeyCode::F10 => CVirtualKeyCode::F10,
      WVirtualKeyCode::F11 => CVirtualKeyCode::F11,
      WVirtualKeyCode::F12 => CVirtualKeyCode::F12,
      WVirtualKeyCode::F13 => CVirtualKeyCode::F13,
      WVirtualKeyCode::F14 => CVirtualKeyCode::F14,
      WVirtualKeyCode::F15 => CVirtualKeyCode::F15,
      WVirtualKeyCode::F16 => CVirtualKeyCode::F16,
      WVirtualKeyCode::F17 => CVirtualKeyCode::F17,
      WVirtualKeyCode::F18 => CVirtualKeyCode::F18,
      WVirtualKeyCode::F19 => CVirtualKeyCode::F19,
      WVirtualKeyCode::F20 => CVirtualKeyCode::F20,
      WVirtualKeyCode::F21 => CVirtualKeyCode::F21,
      WVirtualKeyCode::F22 => CVirtualKeyCode::F22,
      WVirtualKeyCode::F23 => CVirtualKeyCode::F23,
      WVirtualKeyCode::F24 => CVirtualKeyCode::F24,

      WVirtualKeyCode::Snapshot => CVirtualKeyCode::Snapshot,
      WVirtualKeyCode::Scroll => CVirtualKeyCode::Scroll,
      WVirtualKeyCode::Pause => CVirtualKeyCode::Pause,

      WVirtualKeyCode::Insert => CVirtualKeyCode::Insert,
      WVirtualKeyCode::Home => CVirtualKeyCode::Home,
      WVirtualKeyCode::Delete => CVirtualKeyCode::Delete,
      WVirtualKeyCode::End => CVirtualKeyCode::End,
      WVirtualKeyCode::PageDown => CVirtualKeyCode::PageDown,
      WVirtualKeyCode::PageUp => CVirtualKeyCode::PageUp,

      WVirtualKeyCode::Left => CVirtualKeyCode::Left,
      WVirtualKeyCode::Up => CVirtualKeyCode::Up,
      WVirtualKeyCode::Right => CVirtualKeyCode::Right,
      WVirtualKeyCode::Down => CVirtualKeyCode::Down,

      WVirtualKeyCode::Back => CVirtualKeyCode::Back,
      WVirtualKeyCode::Return => CVirtualKeyCode::Return,
      WVirtualKeyCode::Space => CVirtualKeyCode::Space,

      WVirtualKeyCode::Compose => CVirtualKeyCode::Compose,

      WVirtualKeyCode::Caret => CVirtualKeyCode::Caret,

      WVirtualKeyCode::Numlock => CVirtualKeyCode::Numlock,
      WVirtualKeyCode::Numpad0 => CVirtualKeyCode::Numpad0,
      WVirtualKeyCode::Numpad1 => CVirtualKeyCode::Numpad1,
      WVirtualKeyCode::Numpad2 => CVirtualKeyCode::Numpad2,
      WVirtualKeyCode::Numpad3 => CVirtualKeyCode::Numpad3,
      WVirtualKeyCode::Numpad4 => CVirtualKeyCode::Numpad4,
      WVirtualKeyCode::Numpad5 => CVirtualKeyCode::Numpad5,
      WVirtualKeyCode::Numpad6 => CVirtualKeyCode::Numpad6,
      WVirtualKeyCode::Numpad7 => CVirtualKeyCode::Numpad7,
      WVirtualKeyCode::Numpad8 => CVirtualKeyCode::Numpad8,
      WVirtualKeyCode::Numpad9 => CVirtualKeyCode::Numpad9,
      WVirtualKeyCode::NumpadAdd => CVirtualKeyCode::NumpadAdd,
      WVirtualKeyCode::NumpadDivide => CVirtualKeyCode::NumpadDivide,
      WVirtualKeyCode::NumpadDecimal => CVirtualKeyCode::NumpadDecimal,
      WVirtualKeyCode::NumpadComma => CVirtualKeyCode::NumpadComma,
      WVirtualKeyCode::NumpadEnter => CVirtualKeyCode::NumpadEnter,
      WVirtualKeyCode::NumpadEquals => CVirtualKeyCode::NumpadEquals,
      WVirtualKeyCode::NumpadMultiply => CVirtualKeyCode::NumpadMultiply,
      WVirtualKeyCode::NumpadSubtract => CVirtualKeyCode::NumpadSubtract,

      WVirtualKeyCode::AbntC1 => CVirtualKeyCode::AbntC1,
      WVirtualKeyCode::AbntC2 => CVirtualKeyCode::AbntC2,
      WVirtualKeyCode::Apostrophe => CVirtualKeyCode::Apostrophe,
      WVirtualKeyCode::Apps => CVirtualKeyCode::Apps,
      WVirtualKeyCode::Asterisk => CVirtualKeyCode::Asterisk,
      WVirtualKeyCode::At => CVirtualKeyCode::At,
      WVirtualKeyCode::Ax => CVirtualKeyCode::Ax,
      WVirtualKeyCode::Backslash => CVirtualKeyCode::Backslash,
      WVirtualKeyCode::Calculator => CVirtualKeyCode::Calculator,
      WVirtualKeyCode::Capital => CVirtualKeyCode::Capital,
      WVirtualKeyCode::Colon => CVirtualKeyCode::Colon,
      WVirtualKeyCode::Comma => CVirtualKeyCode::Comma,
      WVirtualKeyCode::Convert => CVirtualKeyCode::Convert,
      WVirtualKeyCode::Equals => CVirtualKeyCode::Equals,
      WVirtualKeyCode::Grave => CVirtualKeyCode::Grave,
      WVirtualKeyCode::Kana => CVirtualKeyCode::Kana,
      WVirtualKeyCode::Kanji => CVirtualKeyCode::Kanji,
      WVirtualKeyCode::LAlt => CVirtualKeyCode::LAlt,
      WVirtualKeyCode::LBracket => CVirtualKeyCode::LBracket,
      WVirtualKeyCode::LControl => CVirtualKeyCode::LControl,
      WVirtualKeyCode::LShift => CVirtualKeyCode::LShift,
      WVirtualKeyCode::LWin => CVirtualKeyCode::LWin,
      WVirtualKeyCode::Mail => CVirtualKeyCode::Mail,
      WVirtualKeyCode::MediaSelect => CVirtualKeyCode::MediaSelect,
      WVirtualKeyCode::MediaStop => CVirtualKeyCode::MediaStop,
      WVirtualKeyCode::Minus => CVirtualKeyCode::Minus,
      WVirtualKeyCode::Mute => CVirtualKeyCode::Mute,
      WVirtualKeyCode::MyComputer => CVirtualKeyCode::MyComputer,
      WVirtualKeyCode::NavigateForward => CVirtualKeyCode::NavigateForward,
      WVirtualKeyCode::NavigateBackward => CVirtualKeyCode::NavigateBackward,
      WVirtualKeyCode::NextTrack => CVirtualKeyCode::NextTrack,
      WVirtualKeyCode::NoConvert => CVirtualKeyCode::NoConvert,
      WVirtualKeyCode::OEM102 => CVirtualKeyCode::OEM102,
      WVirtualKeyCode::Period => CVirtualKeyCode::Period,
      WVirtualKeyCode::PlayPause => CVirtualKeyCode::PlayPause,
      WVirtualKeyCode::Plus => CVirtualKeyCode::Plus,
      WVirtualKeyCode::Power => CVirtualKeyCode::Power,
      WVirtualKeyCode::PrevTrack => CVirtualKeyCode::PrevTrack,
      WVirtualKeyCode::RAlt => CVirtualKeyCode::RAlt,
      WVirtualKeyCode::RBracket => CVirtualKeyCode::RBracket,
      WVirtualKeyCode::RControl => CVirtualKeyCode::RControl,
      WVirtualKeyCode::RShift => CVirtualKeyCode::RShift,
      WVirtualKeyCode::RWin => CVirtualKeyCode::RWin,
      WVirtualKeyCode::Semicolon => CVirtualKeyCode::Semicolon,
      WVirtualKeyCode::Slash => CVirtualKeyCode::Slash,
      WVirtualKeyCode::Sleep => CVirtualKeyCode::Sleep,
      WVirtualKeyCode::Stop => CVirtualKeyCode::Stop,
      WVirtualKeyCode::Sysrq => CVirtualKeyCode::Sysrq,
      WVirtualKeyCode::Tab => CVirtualKeyCode::Tab,
      WVirtualKeyCode::Underline => CVirtualKeyCode::Underline,
      WVirtualKeyCode::Unlabeled => CVirtualKeyCode::Unlabeled,
      WVirtualKeyCode::VolumeDown => CVirtualKeyCode::VolumeDown,
      WVirtualKeyCode::VolumeUp => CVirtualKeyCode::VolumeUp,
      WVirtualKeyCode::Wake => CVirtualKeyCode::Wake,
      WVirtualKeyCode::WebBack => CVirtualKeyCode::WebBack,
      WVirtualKeyCode::WebFavorites => CVirtualKeyCode::WebFavorites,
      WVirtualKeyCode::WebForward => CVirtualKeyCode::WebForward,
      WVirtualKeyCode::WebHome => CVirtualKeyCode::WebHome,
      WVirtualKeyCode::WebRefresh => CVirtualKeyCode::WebRefresh,
      WVirtualKeyCode::WebSearch => CVirtualKeyCode::WebSearch,
      WVirtualKeyCode::WebStop => CVirtualKeyCode::WebStop,
      WVirtualKeyCode::Yen => CVirtualKeyCode::Yen,
      WVirtualKeyCode::Copy => CVirtualKeyCode::Copy,
      WVirtualKeyCode::Paste => CVirtualKeyCode::Paste,
      WVirtualKeyCode::Cut => CVirtualKeyCode::Cut,
    }
  }
}

impl From<CVirtualKeyCode> for RVirtualKeyCode {
  fn from(value: CVirtualKeyCode) -> RVirtualKeyCode {
    let kc = match value {
      CVirtualKeyCode::Key1 => WVirtualKeyCode::Key1,
      CVirtualKeyCode::Key2 => WVirtualKeyCode::Key2,
      CVirtualKeyCode::Key3 => WVirtualKeyCode::Key3,
      CVirtualKeyCode::Key4 => WVirtualKeyCode::Key4,
      CVirtualKeyCode::Key5 => WVirtualKeyCode::Key5,
      CVirtualKeyCode::Key6 => WVirtualKeyCode::Key6,
      CVirtualKeyCode::Key7 => WVirtualKeyCode::Key7,
      CVirtualKeyCode::Key8 => WVirtualKeyCode::Key8,
      CVirtualKeyCode::Key9 => WVirtualKeyCode::Key9,
      CVirtualKeyCode::Key0 => WVirtualKeyCode::Key0,

      CVirtualKeyCode::A => WVirtualKeyCode::A,
      CVirtualKeyCode::B => WVirtualKeyCode::B,
      CVirtualKeyCode::C => WVirtualKeyCode::C,
      CVirtualKeyCode::D => WVirtualKeyCode::D,
      CVirtualKeyCode::E => WVirtualKeyCode::E,
      CVirtualKeyCode::F => WVirtualKeyCode::F,
      CVirtualKeyCode::G => WVirtualKeyCode::G,
      CVirtualKeyCode::H => WVirtualKeyCode::H,
      CVirtualKeyCode::I => WVirtualKeyCode::I,
      CVirtualKeyCode::J => WVirtualKeyCode::J,
      CVirtualKeyCode::K => WVirtualKeyCode::K,
      CVirtualKeyCode::L => WVirtualKeyCode::L,
      CVirtualKeyCode::M => WVirtualKeyCode::M,
      CVirtualKeyCode::N => WVirtualKeyCode::N,
      CVirtualKeyCode::O => WVirtualKeyCode::O,
      CVirtualKeyCode::P => WVirtualKeyCode::P,
      CVirtualKeyCode::Q => WVirtualKeyCode::Q,
      CVirtualKeyCode::R => WVirtualKeyCode::R,
      CVirtualKeyCode::S => WVirtualKeyCode::S,
      CVirtualKeyCode::T => WVirtualKeyCode::T,
      CVirtualKeyCode::U => WVirtualKeyCode::U,
      CVirtualKeyCode::V => WVirtualKeyCode::V,
      CVirtualKeyCode::W => WVirtualKeyCode::W,
      CVirtualKeyCode::X => WVirtualKeyCode::X,
      CVirtualKeyCode::Y => WVirtualKeyCode::Y,
      CVirtualKeyCode::Z => WVirtualKeyCode::Z,

      CVirtualKeyCode::Escape => WVirtualKeyCode::Escape,

      CVirtualKeyCode::F1 => WVirtualKeyCode::F1,
      CVirtualKeyCode::F2 => WVirtualKeyCode::F2,
      CVirtualKeyCode::F3 => WVirtualKeyCode::F3,
      CVirtualKeyCode::F4 => WVirtualKeyCode::F4,
      CVirtualKeyCode::F5 => WVirtualKeyCode::F5,
      CVirtualKeyCode::F6 => WVirtualKeyCode::F6,
      CVirtualKeyCode::F7 => WVirtualKeyCode::F7,
      CVirtualKeyCode::F8 => WVirtualKeyCode::F8,
      CVirtualKeyCode::F9 => WVirtualKeyCode::F9,
      CVirtualKeyCode::F10 => WVirtualKeyCode::F10,
      CVirtualKeyCode::F11 => WVirtualKeyCode::F11,
      CVirtualKeyCode::F12 => WVirtualKeyCode::F12,
      CVirtualKeyCode::F13 => WVirtualKeyCode::F13,
      CVirtualKeyCode::F14 => WVirtualKeyCode::F14,
      CVirtualKeyCode::F15 => WVirtualKeyCode::F15,
      CVirtualKeyCode::F16 => WVirtualKeyCode::F16,
      CVirtualKeyCode::F17 => WVirtualKeyCode::F17,
      CVirtualKeyCode::F18 => WVirtualKeyCode::F18,
      CVirtualKeyCode::F19 => WVirtualKeyCode::F19,
      CVirtualKeyCode::F20 => WVirtualKeyCode::F20,
      CVirtualKeyCode::F21 => WVirtualKeyCode::F21,
      CVirtualKeyCode::F22 => WVirtualKeyCode::F22,
      CVirtualKeyCode::F23 => WVirtualKeyCode::F23,
      CVirtualKeyCode::F24 => WVirtualKeyCode::F24,

      CVirtualKeyCode::Snapshot => WVirtualKeyCode::Snapshot,
      CVirtualKeyCode::Scroll => WVirtualKeyCode::Scroll,
      CVirtualKeyCode::Pause => WVirtualKeyCode::Pause,

      CVirtualKeyCode::Insert => WVirtualKeyCode::Insert,
      CVirtualKeyCode::Home => WVirtualKeyCode::Home,
      CVirtualKeyCode::Delete => WVirtualKeyCode::Delete,
      CVirtualKeyCode::End => WVirtualKeyCode::End,
      CVirtualKeyCode::PageDown => WVirtualKeyCode::PageDown,
      CVirtualKeyCode::PageUp => WVirtualKeyCode::PageUp,

      CVirtualKeyCode::Left => WVirtualKeyCode::Left,
      CVirtualKeyCode::Up => WVirtualKeyCode::Up,
      CVirtualKeyCode::Right => WVirtualKeyCode::Right,
      CVirtualKeyCode::Down => WVirtualKeyCode::Down,

      CVirtualKeyCode::Back => WVirtualKeyCode::Back,
      CVirtualKeyCode::Return => WVirtualKeyCode::Return,
      CVirtualKeyCode::Space => WVirtualKeyCode::Space,

      CVirtualKeyCode::Compose => WVirtualKeyCode::Compose,

      CVirtualKeyCode::Caret => WVirtualKeyCode::Caret,

      CVirtualKeyCode::Numlock => WVirtualKeyCode::Numlock,
      CVirtualKeyCode::Numpad0 => WVirtualKeyCode::Numpad0,
      CVirtualKeyCode::Numpad1 => WVirtualKeyCode::Numpad1,
      CVirtualKeyCode::Numpad2 => WVirtualKeyCode::Numpad2,
      CVirtualKeyCode::Numpad3 => WVirtualKeyCode::Numpad3,
      CVirtualKeyCode::Numpad4 => WVirtualKeyCode::Numpad4,
      CVirtualKeyCode::Numpad5 => WVirtualKeyCode::Numpad5,
      CVirtualKeyCode::Numpad6 => WVirtualKeyCode::Numpad6,
      CVirtualKeyCode::Numpad7 => WVirtualKeyCode::Numpad7,
      CVirtualKeyCode::Numpad8 => WVirtualKeyCode::Numpad8,
      CVirtualKeyCode::Numpad9 => WVirtualKeyCode::Numpad9,
      CVirtualKeyCode::NumpadAdd => WVirtualKeyCode::NumpadAdd,
      CVirtualKeyCode::NumpadDivide => WVirtualKeyCode::NumpadDivide,
      CVirtualKeyCode::NumpadDecimal => WVirtualKeyCode::NumpadDecimal,
      CVirtualKeyCode::NumpadComma => WVirtualKeyCode::NumpadComma,
      CVirtualKeyCode::NumpadEnter => WVirtualKeyCode::NumpadEnter,
      CVirtualKeyCode::NumpadEquals => WVirtualKeyCode::NumpadEquals,
      CVirtualKeyCode::NumpadMultiply => WVirtualKeyCode::NumpadMultiply,
      CVirtualKeyCode::NumpadSubtract => WVirtualKeyCode::NumpadSubtract,

      CVirtualKeyCode::AbntC1 => WVirtualKeyCode::AbntC1,
      CVirtualKeyCode::AbntC2 => WVirtualKeyCode::AbntC2,
      CVirtualKeyCode::Apostrophe => WVirtualKeyCode::Apostrophe,
      CVirtualKeyCode::Apps => WVirtualKeyCode::Apps,
      CVirtualKeyCode::Asterisk => WVirtualKeyCode::Asterisk,
      CVirtualKeyCode::At => WVirtualKeyCode::At,
      CVirtualKeyCode::Ax => WVirtualKeyCode::Ax,
      CVirtualKeyCode::Backslash => WVirtualKeyCode::Backslash,
      CVirtualKeyCode::Calculator => WVirtualKeyCode::Calculator,
      CVirtualKeyCode::Capital => WVirtualKeyCode::Capital,
      CVirtualKeyCode::Colon => WVirtualKeyCode::Colon,
      CVirtualKeyCode::Comma => WVirtualKeyCode::Comma,
      CVirtualKeyCode::Convert => WVirtualKeyCode::Convert,
      CVirtualKeyCode::Equals => WVirtualKeyCode::Equals,
      CVirtualKeyCode::Grave => WVirtualKeyCode::Grave,
      CVirtualKeyCode::Kana => WVirtualKeyCode::Kana,
      CVirtualKeyCode::Kanji => WVirtualKeyCode::Kanji,
      CVirtualKeyCode::LAlt => WVirtualKeyCode::LAlt,
      CVirtualKeyCode::LBracket => WVirtualKeyCode::LBracket,
      CVirtualKeyCode::LControl => WVirtualKeyCode::LControl,
      CVirtualKeyCode::LShift => WVirtualKeyCode::LShift,
      CVirtualKeyCode::LWin => WVirtualKeyCode::LWin,
      CVirtualKeyCode::Mail => WVirtualKeyCode::Mail,
      CVirtualKeyCode::MediaSelect => WVirtualKeyCode::MediaSelect,
      CVirtualKeyCode::MediaStop => WVirtualKeyCode::MediaStop,
      CVirtualKeyCode::Minus => WVirtualKeyCode::Minus,
      CVirtualKeyCode::Mute => WVirtualKeyCode::Mute,
      CVirtualKeyCode::MyComputer => WVirtualKeyCode::MyComputer,
      CVirtualKeyCode::NavigateForward => WVirtualKeyCode::NavigateForward,
      CVirtualKeyCode::NavigateBackward => WVirtualKeyCode::NavigateBackward,
      CVirtualKeyCode::NextTrack => WVirtualKeyCode::NextTrack,
      CVirtualKeyCode::NoConvert => WVirtualKeyCode::NoConvert,
      CVirtualKeyCode::OEM102 => WVirtualKeyCode::OEM102,
      CVirtualKeyCode::Period => WVirtualKeyCode::Period,
      CVirtualKeyCode::PlayPause => WVirtualKeyCode::PlayPause,
      CVirtualKeyCode::Plus => WVirtualKeyCode::Plus,
      CVirtualKeyCode::Power => WVirtualKeyCode::Power,
      CVirtualKeyCode::PrevTrack => WVirtualKeyCode::PrevTrack,
      CVirtualKeyCode::RAlt => WVirtualKeyCode::RAlt,
      CVirtualKeyCode::RBracket => WVirtualKeyCode::RBracket,
      CVirtualKeyCode::RControl => WVirtualKeyCode::RControl,
      CVirtualKeyCode::RShift => WVirtualKeyCode::RShift,
      CVirtualKeyCode::RWin => WVirtualKeyCode::RWin,
      CVirtualKeyCode::Semicolon => WVirtualKeyCode::Semicolon,
      CVirtualKeyCode::Slash => WVirtualKeyCode::Slash,
      CVirtualKeyCode::Sleep => WVirtualKeyCode::Sleep,
      CVirtualKeyCode::Stop => WVirtualKeyCode::Stop,
      CVirtualKeyCode::Sysrq => WVirtualKeyCode::Sysrq,
      CVirtualKeyCode::Tab => WVirtualKeyCode::Tab,
      CVirtualKeyCode::Underline => WVirtualKeyCode::Underline,
      CVirtualKeyCode::Unlabeled => WVirtualKeyCode::Unlabeled,
      CVirtualKeyCode::VolumeDown => WVirtualKeyCode::VolumeDown,
      CVirtualKeyCode::VolumeUp => WVirtualKeyCode::VolumeUp,
      CVirtualKeyCode::Wake => WVirtualKeyCode::Wake,
      CVirtualKeyCode::WebBack => WVirtualKeyCode::WebBack,
      CVirtualKeyCode::WebFavorites => WVirtualKeyCode::WebFavorites,
      CVirtualKeyCode::WebForward => WVirtualKeyCode::WebForward,
      CVirtualKeyCode::WebHome => WVirtualKeyCode::WebHome,
      CVirtualKeyCode::WebRefresh => WVirtualKeyCode::WebRefresh,
      CVirtualKeyCode::WebSearch => WVirtualKeyCode::WebSearch,
      CVirtualKeyCode::WebStop => WVirtualKeyCode::WebStop,
      CVirtualKeyCode::Yen => WVirtualKeyCode::Yen,
      CVirtualKeyCode::Copy => WVirtualKeyCode::Copy,
      CVirtualKeyCode::Paste => WVirtualKeyCode::Paste,
      CVirtualKeyCode::Cut => WVirtualKeyCode::Cut,
    };
    kc.into()
  }
}
