use ribir_core::prelude::VirtualKeyCode as RibirVirtualKeyCode;
use winit::event::VirtualKeyCode as WinitVirtualKeyCode;

pub struct WrappedVirtualKeyCode(WinitVirtualKeyCode);

impl From<WinitVirtualKeyCode> for WrappedVirtualKeyCode {
  fn from(value: WinitVirtualKeyCode) -> Self { WrappedVirtualKeyCode(value) }
}

impl From<WrappedVirtualKeyCode> for WinitVirtualKeyCode {
  fn from(val: WrappedVirtualKeyCode) -> Self { val.0 }
}

impl From<WrappedVirtualKeyCode> for RibirVirtualKeyCode {
  fn from(val: WrappedVirtualKeyCode) -> Self {
    match val.0 {
      WinitVirtualKeyCode::Key1 => RibirVirtualKeyCode::Key1,
      WinitVirtualKeyCode::Key2 => RibirVirtualKeyCode::Key2,
      WinitVirtualKeyCode::Key3 => RibirVirtualKeyCode::Key3,
      WinitVirtualKeyCode::Key4 => RibirVirtualKeyCode::Key4,
      WinitVirtualKeyCode::Key5 => RibirVirtualKeyCode::Key5,
      WinitVirtualKeyCode::Key6 => RibirVirtualKeyCode::Key6,
      WinitVirtualKeyCode::Key7 => RibirVirtualKeyCode::Key7,
      WinitVirtualKeyCode::Key8 => RibirVirtualKeyCode::Key8,
      WinitVirtualKeyCode::Key9 => RibirVirtualKeyCode::Key9,
      WinitVirtualKeyCode::Key0 => RibirVirtualKeyCode::Key0,

      WinitVirtualKeyCode::A => RibirVirtualKeyCode::A,
      WinitVirtualKeyCode::B => RibirVirtualKeyCode::B,
      WinitVirtualKeyCode::C => RibirVirtualKeyCode::C,
      WinitVirtualKeyCode::D => RibirVirtualKeyCode::D,
      WinitVirtualKeyCode::E => RibirVirtualKeyCode::E,
      WinitVirtualKeyCode::F => RibirVirtualKeyCode::F,
      WinitVirtualKeyCode::G => RibirVirtualKeyCode::G,
      WinitVirtualKeyCode::H => RibirVirtualKeyCode::H,
      WinitVirtualKeyCode::I => RibirVirtualKeyCode::I,
      WinitVirtualKeyCode::J => RibirVirtualKeyCode::J,
      WinitVirtualKeyCode::K => RibirVirtualKeyCode::K,
      WinitVirtualKeyCode::L => RibirVirtualKeyCode::L,
      WinitVirtualKeyCode::M => RibirVirtualKeyCode::M,
      WinitVirtualKeyCode::N => RibirVirtualKeyCode::N,
      WinitVirtualKeyCode::O => RibirVirtualKeyCode::O,
      WinitVirtualKeyCode::P => RibirVirtualKeyCode::P,
      WinitVirtualKeyCode::Q => RibirVirtualKeyCode::Q,
      WinitVirtualKeyCode::R => RibirVirtualKeyCode::R,
      WinitVirtualKeyCode::S => RibirVirtualKeyCode::S,
      WinitVirtualKeyCode::T => RibirVirtualKeyCode::T,
      WinitVirtualKeyCode::U => RibirVirtualKeyCode::U,
      WinitVirtualKeyCode::V => RibirVirtualKeyCode::V,
      WinitVirtualKeyCode::W => RibirVirtualKeyCode::W,
      WinitVirtualKeyCode::X => RibirVirtualKeyCode::X,
      WinitVirtualKeyCode::Y => RibirVirtualKeyCode::Y,
      WinitVirtualKeyCode::Z => RibirVirtualKeyCode::Z,

      WinitVirtualKeyCode::Escape => RibirVirtualKeyCode::Escape,

      WinitVirtualKeyCode::F1 => RibirVirtualKeyCode::F1,
      WinitVirtualKeyCode::F2 => RibirVirtualKeyCode::F2,
      WinitVirtualKeyCode::F3 => RibirVirtualKeyCode::F3,
      WinitVirtualKeyCode::F4 => RibirVirtualKeyCode::F4,
      WinitVirtualKeyCode::F5 => RibirVirtualKeyCode::F5,
      WinitVirtualKeyCode::F6 => RibirVirtualKeyCode::F6,
      WinitVirtualKeyCode::F7 => RibirVirtualKeyCode::F7,
      WinitVirtualKeyCode::F8 => RibirVirtualKeyCode::F8,
      WinitVirtualKeyCode::F9 => RibirVirtualKeyCode::F9,
      WinitVirtualKeyCode::F10 => RibirVirtualKeyCode::F10,
      WinitVirtualKeyCode::F11 => RibirVirtualKeyCode::F11,
      WinitVirtualKeyCode::F12 => RibirVirtualKeyCode::F12,
      WinitVirtualKeyCode::F13 => RibirVirtualKeyCode::F13,
      WinitVirtualKeyCode::F14 => RibirVirtualKeyCode::F14,
      WinitVirtualKeyCode::F15 => RibirVirtualKeyCode::F15,
      WinitVirtualKeyCode::F16 => RibirVirtualKeyCode::F16,
      WinitVirtualKeyCode::F17 => RibirVirtualKeyCode::F17,
      WinitVirtualKeyCode::F18 => RibirVirtualKeyCode::F18,
      WinitVirtualKeyCode::F19 => RibirVirtualKeyCode::F19,
      WinitVirtualKeyCode::F20 => RibirVirtualKeyCode::F20,
      WinitVirtualKeyCode::F21 => RibirVirtualKeyCode::F21,
      WinitVirtualKeyCode::F22 => RibirVirtualKeyCode::F22,
      WinitVirtualKeyCode::F23 => RibirVirtualKeyCode::F23,
      WinitVirtualKeyCode::F24 => RibirVirtualKeyCode::F24,

      WinitVirtualKeyCode::Snapshot => RibirVirtualKeyCode::Snapshot,
      WinitVirtualKeyCode::Scroll => RibirVirtualKeyCode::Scroll,
      WinitVirtualKeyCode::Pause => RibirVirtualKeyCode::Pause,

      WinitVirtualKeyCode::Insert => RibirVirtualKeyCode::Insert,
      WinitVirtualKeyCode::Home => RibirVirtualKeyCode::Home,
      WinitVirtualKeyCode::Delete => RibirVirtualKeyCode::Delete,
      WinitVirtualKeyCode::End => RibirVirtualKeyCode::End,
      WinitVirtualKeyCode::PageDown => RibirVirtualKeyCode::PageDown,
      WinitVirtualKeyCode::PageUp => RibirVirtualKeyCode::PageUp,

      WinitVirtualKeyCode::Left => RibirVirtualKeyCode::Left,
      WinitVirtualKeyCode::Up => RibirVirtualKeyCode::Up,
      WinitVirtualKeyCode::Right => RibirVirtualKeyCode::Right,
      WinitVirtualKeyCode::Down => RibirVirtualKeyCode::Down,

      WinitVirtualKeyCode::Back => RibirVirtualKeyCode::Back,
      WinitVirtualKeyCode::Return => RibirVirtualKeyCode::Return,
      WinitVirtualKeyCode::Space => RibirVirtualKeyCode::Space,

      WinitVirtualKeyCode::Compose => RibirVirtualKeyCode::Compose,

      WinitVirtualKeyCode::Caret => RibirVirtualKeyCode::Caret,

      WinitVirtualKeyCode::Numlock => RibirVirtualKeyCode::Numlock,
      WinitVirtualKeyCode::Numpad0 => RibirVirtualKeyCode::Numpad0,
      WinitVirtualKeyCode::Numpad1 => RibirVirtualKeyCode::Numpad1,
      WinitVirtualKeyCode::Numpad2 => RibirVirtualKeyCode::Numpad2,
      WinitVirtualKeyCode::Numpad3 => RibirVirtualKeyCode::Numpad3,
      WinitVirtualKeyCode::Numpad4 => RibirVirtualKeyCode::Numpad4,
      WinitVirtualKeyCode::Numpad5 => RibirVirtualKeyCode::Numpad5,
      WinitVirtualKeyCode::Numpad6 => RibirVirtualKeyCode::Numpad6,
      WinitVirtualKeyCode::Numpad7 => RibirVirtualKeyCode::Numpad7,
      WinitVirtualKeyCode::Numpad8 => RibirVirtualKeyCode::Numpad8,
      WinitVirtualKeyCode::Numpad9 => RibirVirtualKeyCode::Numpad9,
      WinitVirtualKeyCode::NumpadAdd => RibirVirtualKeyCode::NumpadAdd,
      WinitVirtualKeyCode::NumpadDivide => RibirVirtualKeyCode::NumpadDivide,
      WinitVirtualKeyCode::NumpadDecimal => RibirVirtualKeyCode::NumpadDecimal,
      WinitVirtualKeyCode::NumpadComma => RibirVirtualKeyCode::NumpadComma,
      WinitVirtualKeyCode::NumpadEnter => RibirVirtualKeyCode::NumpadEnter,
      WinitVirtualKeyCode::NumpadEquals => RibirVirtualKeyCode::NumpadEquals,
      WinitVirtualKeyCode::NumpadMultiply => RibirVirtualKeyCode::NumpadMultiply,
      WinitVirtualKeyCode::NumpadSubtract => RibirVirtualKeyCode::NumpadSubtract,

      WinitVirtualKeyCode::AbntC1 => RibirVirtualKeyCode::AbntC1,
      WinitVirtualKeyCode::AbntC2 => RibirVirtualKeyCode::AbntC2,
      WinitVirtualKeyCode::Apostrophe => RibirVirtualKeyCode::Apostrophe,
      WinitVirtualKeyCode::Apps => RibirVirtualKeyCode::Apps,
      WinitVirtualKeyCode::Asterisk => RibirVirtualKeyCode::Asterisk,
      WinitVirtualKeyCode::At => RibirVirtualKeyCode::At,
      WinitVirtualKeyCode::Ax => RibirVirtualKeyCode::Ax,
      WinitVirtualKeyCode::Backslash => RibirVirtualKeyCode::Backslash,
      WinitVirtualKeyCode::Calculator => RibirVirtualKeyCode::Calculator,
      WinitVirtualKeyCode::Capital => RibirVirtualKeyCode::Capital,
      WinitVirtualKeyCode::Colon => RibirVirtualKeyCode::Colon,
      WinitVirtualKeyCode::Comma => RibirVirtualKeyCode::Comma,
      WinitVirtualKeyCode::Convert => RibirVirtualKeyCode::Convert,
      WinitVirtualKeyCode::Equals => RibirVirtualKeyCode::Equals,
      WinitVirtualKeyCode::Grave => RibirVirtualKeyCode::Grave,
      WinitVirtualKeyCode::Kana => RibirVirtualKeyCode::Kana,
      WinitVirtualKeyCode::Kanji => RibirVirtualKeyCode::Kanji,
      WinitVirtualKeyCode::LAlt => RibirVirtualKeyCode::LAlt,
      WinitVirtualKeyCode::LBracket => RibirVirtualKeyCode::LBracket,
      WinitVirtualKeyCode::LControl => RibirVirtualKeyCode::LControl,
      WinitVirtualKeyCode::LShift => RibirVirtualKeyCode::LShift,
      WinitVirtualKeyCode::LWin => RibirVirtualKeyCode::LWin,
      WinitVirtualKeyCode::Mail => RibirVirtualKeyCode::Mail,
      WinitVirtualKeyCode::MediaSelect => RibirVirtualKeyCode::MediaSelect,
      WinitVirtualKeyCode::MediaStop => RibirVirtualKeyCode::MediaStop,
      WinitVirtualKeyCode::Minus => RibirVirtualKeyCode::Minus,
      WinitVirtualKeyCode::Mute => RibirVirtualKeyCode::Mute,
      WinitVirtualKeyCode::MyComputer => RibirVirtualKeyCode::MyComputer,
      WinitVirtualKeyCode::NavigateForward => RibirVirtualKeyCode::NavigateForward,
      WinitVirtualKeyCode::NavigateBackward => RibirVirtualKeyCode::NavigateBackward,
      WinitVirtualKeyCode::NextTrack => RibirVirtualKeyCode::NextTrack,
      WinitVirtualKeyCode::NoConvert => RibirVirtualKeyCode::NoConvert,
      WinitVirtualKeyCode::OEM102 => RibirVirtualKeyCode::OEM102,
      WinitVirtualKeyCode::Period => RibirVirtualKeyCode::Period,
      WinitVirtualKeyCode::PlayPause => RibirVirtualKeyCode::PlayPause,
      WinitVirtualKeyCode::Plus => RibirVirtualKeyCode::Plus,
      WinitVirtualKeyCode::Power => RibirVirtualKeyCode::Power,
      WinitVirtualKeyCode::PrevTrack => RibirVirtualKeyCode::PrevTrack,
      WinitVirtualKeyCode::RAlt => RibirVirtualKeyCode::RAlt,
      WinitVirtualKeyCode::RBracket => RibirVirtualKeyCode::RBracket,
      WinitVirtualKeyCode::RControl => RibirVirtualKeyCode::RControl,
      WinitVirtualKeyCode::RShift => RibirVirtualKeyCode::RShift,
      WinitVirtualKeyCode::RWin => RibirVirtualKeyCode::RWin,
      WinitVirtualKeyCode::Semicolon => RibirVirtualKeyCode::Semicolon,
      WinitVirtualKeyCode::Slash => RibirVirtualKeyCode::Slash,
      WinitVirtualKeyCode::Sleep => RibirVirtualKeyCode::Sleep,
      WinitVirtualKeyCode::Stop => RibirVirtualKeyCode::Stop,
      WinitVirtualKeyCode::Sysrq => RibirVirtualKeyCode::Sysrq,
      WinitVirtualKeyCode::Tab => RibirVirtualKeyCode::Tab,
      WinitVirtualKeyCode::Underline => RibirVirtualKeyCode::Underline,
      WinitVirtualKeyCode::Unlabeled => RibirVirtualKeyCode::Unlabeled,
      WinitVirtualKeyCode::VolumeDown => RibirVirtualKeyCode::VolumeDown,
      WinitVirtualKeyCode::VolumeUp => RibirVirtualKeyCode::VolumeUp,
      WinitVirtualKeyCode::Wake => RibirVirtualKeyCode::Wake,
      WinitVirtualKeyCode::WebBack => RibirVirtualKeyCode::WebBack,
      WinitVirtualKeyCode::WebFavorites => RibirVirtualKeyCode::WebFavorites,
      WinitVirtualKeyCode::WebForward => RibirVirtualKeyCode::WebForward,
      WinitVirtualKeyCode::WebHome => RibirVirtualKeyCode::WebHome,
      WinitVirtualKeyCode::WebRefresh => RibirVirtualKeyCode::WebRefresh,
      WinitVirtualKeyCode::WebSearch => RibirVirtualKeyCode::WebSearch,
      WinitVirtualKeyCode::WebStop => RibirVirtualKeyCode::WebStop,
      WinitVirtualKeyCode::Yen => RibirVirtualKeyCode::Yen,
      WinitVirtualKeyCode::Copy => RibirVirtualKeyCode::Copy,
      WinitVirtualKeyCode::Paste => RibirVirtualKeyCode::Paste,
      WinitVirtualKeyCode::Cut => RibirVirtualKeyCode::Cut,
    }
  }
}

impl From<RibirVirtualKeyCode> for WrappedVirtualKeyCode {
  fn from(value: RibirVirtualKeyCode) -> WrappedVirtualKeyCode {
    let kc = match value {
      RibirVirtualKeyCode::Key1 => WinitVirtualKeyCode::Key1,
      RibirVirtualKeyCode::Key2 => WinitVirtualKeyCode::Key2,
      RibirVirtualKeyCode::Key3 => WinitVirtualKeyCode::Key3,
      RibirVirtualKeyCode::Key4 => WinitVirtualKeyCode::Key4,
      RibirVirtualKeyCode::Key5 => WinitVirtualKeyCode::Key5,
      RibirVirtualKeyCode::Key6 => WinitVirtualKeyCode::Key6,
      RibirVirtualKeyCode::Key7 => WinitVirtualKeyCode::Key7,
      RibirVirtualKeyCode::Key8 => WinitVirtualKeyCode::Key8,
      RibirVirtualKeyCode::Key9 => WinitVirtualKeyCode::Key9,
      RibirVirtualKeyCode::Key0 => WinitVirtualKeyCode::Key0,

      RibirVirtualKeyCode::A => WinitVirtualKeyCode::A,
      RibirVirtualKeyCode::B => WinitVirtualKeyCode::B,
      RibirVirtualKeyCode::C => WinitVirtualKeyCode::C,
      RibirVirtualKeyCode::D => WinitVirtualKeyCode::D,
      RibirVirtualKeyCode::E => WinitVirtualKeyCode::E,
      RibirVirtualKeyCode::F => WinitVirtualKeyCode::F,
      RibirVirtualKeyCode::G => WinitVirtualKeyCode::G,
      RibirVirtualKeyCode::H => WinitVirtualKeyCode::H,
      RibirVirtualKeyCode::I => WinitVirtualKeyCode::I,
      RibirVirtualKeyCode::J => WinitVirtualKeyCode::J,
      RibirVirtualKeyCode::K => WinitVirtualKeyCode::K,
      RibirVirtualKeyCode::L => WinitVirtualKeyCode::L,
      RibirVirtualKeyCode::M => WinitVirtualKeyCode::M,
      RibirVirtualKeyCode::N => WinitVirtualKeyCode::N,
      RibirVirtualKeyCode::O => WinitVirtualKeyCode::O,
      RibirVirtualKeyCode::P => WinitVirtualKeyCode::P,
      RibirVirtualKeyCode::Q => WinitVirtualKeyCode::Q,
      RibirVirtualKeyCode::R => WinitVirtualKeyCode::R,
      RibirVirtualKeyCode::S => WinitVirtualKeyCode::S,
      RibirVirtualKeyCode::T => WinitVirtualKeyCode::T,
      RibirVirtualKeyCode::U => WinitVirtualKeyCode::U,
      RibirVirtualKeyCode::V => WinitVirtualKeyCode::V,
      RibirVirtualKeyCode::W => WinitVirtualKeyCode::W,
      RibirVirtualKeyCode::X => WinitVirtualKeyCode::X,
      RibirVirtualKeyCode::Y => WinitVirtualKeyCode::Y,
      RibirVirtualKeyCode::Z => WinitVirtualKeyCode::Z,

      RibirVirtualKeyCode::Escape => WinitVirtualKeyCode::Escape,

      RibirVirtualKeyCode::F1 => WinitVirtualKeyCode::F1,
      RibirVirtualKeyCode::F2 => WinitVirtualKeyCode::F2,
      RibirVirtualKeyCode::F3 => WinitVirtualKeyCode::F3,
      RibirVirtualKeyCode::F4 => WinitVirtualKeyCode::F4,
      RibirVirtualKeyCode::F5 => WinitVirtualKeyCode::F5,
      RibirVirtualKeyCode::F6 => WinitVirtualKeyCode::F6,
      RibirVirtualKeyCode::F7 => WinitVirtualKeyCode::F7,
      RibirVirtualKeyCode::F8 => WinitVirtualKeyCode::F8,
      RibirVirtualKeyCode::F9 => WinitVirtualKeyCode::F9,
      RibirVirtualKeyCode::F10 => WinitVirtualKeyCode::F10,
      RibirVirtualKeyCode::F11 => WinitVirtualKeyCode::F11,
      RibirVirtualKeyCode::F12 => WinitVirtualKeyCode::F12,
      RibirVirtualKeyCode::F13 => WinitVirtualKeyCode::F13,
      RibirVirtualKeyCode::F14 => WinitVirtualKeyCode::F14,
      RibirVirtualKeyCode::F15 => WinitVirtualKeyCode::F15,
      RibirVirtualKeyCode::F16 => WinitVirtualKeyCode::F16,
      RibirVirtualKeyCode::F17 => WinitVirtualKeyCode::F17,
      RibirVirtualKeyCode::F18 => WinitVirtualKeyCode::F18,
      RibirVirtualKeyCode::F19 => WinitVirtualKeyCode::F19,
      RibirVirtualKeyCode::F20 => WinitVirtualKeyCode::F20,
      RibirVirtualKeyCode::F21 => WinitVirtualKeyCode::F21,
      RibirVirtualKeyCode::F22 => WinitVirtualKeyCode::F22,
      RibirVirtualKeyCode::F23 => WinitVirtualKeyCode::F23,
      RibirVirtualKeyCode::F24 => WinitVirtualKeyCode::F24,

      RibirVirtualKeyCode::Snapshot => WinitVirtualKeyCode::Snapshot,
      RibirVirtualKeyCode::Scroll => WinitVirtualKeyCode::Scroll,
      RibirVirtualKeyCode::Pause => WinitVirtualKeyCode::Pause,

      RibirVirtualKeyCode::Insert => WinitVirtualKeyCode::Insert,
      RibirVirtualKeyCode::Home => WinitVirtualKeyCode::Home,
      RibirVirtualKeyCode::Delete => WinitVirtualKeyCode::Delete,
      RibirVirtualKeyCode::End => WinitVirtualKeyCode::End,
      RibirVirtualKeyCode::PageDown => WinitVirtualKeyCode::PageDown,
      RibirVirtualKeyCode::PageUp => WinitVirtualKeyCode::PageUp,

      RibirVirtualKeyCode::Left => WinitVirtualKeyCode::Left,
      RibirVirtualKeyCode::Up => WinitVirtualKeyCode::Up,
      RibirVirtualKeyCode::Right => WinitVirtualKeyCode::Right,
      RibirVirtualKeyCode::Down => WinitVirtualKeyCode::Down,

      RibirVirtualKeyCode::Back => WinitVirtualKeyCode::Back,
      RibirVirtualKeyCode::Return => WinitVirtualKeyCode::Return,
      RibirVirtualKeyCode::Space => WinitVirtualKeyCode::Space,

      RibirVirtualKeyCode::Compose => WinitVirtualKeyCode::Compose,

      RibirVirtualKeyCode::Caret => WinitVirtualKeyCode::Caret,

      RibirVirtualKeyCode::Numlock => WinitVirtualKeyCode::Numlock,
      RibirVirtualKeyCode::Numpad0 => WinitVirtualKeyCode::Numpad0,
      RibirVirtualKeyCode::Numpad1 => WinitVirtualKeyCode::Numpad1,
      RibirVirtualKeyCode::Numpad2 => WinitVirtualKeyCode::Numpad2,
      RibirVirtualKeyCode::Numpad3 => WinitVirtualKeyCode::Numpad3,
      RibirVirtualKeyCode::Numpad4 => WinitVirtualKeyCode::Numpad4,
      RibirVirtualKeyCode::Numpad5 => WinitVirtualKeyCode::Numpad5,
      RibirVirtualKeyCode::Numpad6 => WinitVirtualKeyCode::Numpad6,
      RibirVirtualKeyCode::Numpad7 => WinitVirtualKeyCode::Numpad7,
      RibirVirtualKeyCode::Numpad8 => WinitVirtualKeyCode::Numpad8,
      RibirVirtualKeyCode::Numpad9 => WinitVirtualKeyCode::Numpad9,
      RibirVirtualKeyCode::NumpadAdd => WinitVirtualKeyCode::NumpadAdd,
      RibirVirtualKeyCode::NumpadDivide => WinitVirtualKeyCode::NumpadDivide,
      RibirVirtualKeyCode::NumpadDecimal => WinitVirtualKeyCode::NumpadDecimal,
      RibirVirtualKeyCode::NumpadComma => WinitVirtualKeyCode::NumpadComma,
      RibirVirtualKeyCode::NumpadEnter => WinitVirtualKeyCode::NumpadEnter,
      RibirVirtualKeyCode::NumpadEquals => WinitVirtualKeyCode::NumpadEquals,
      RibirVirtualKeyCode::NumpadMultiply => WinitVirtualKeyCode::NumpadMultiply,
      RibirVirtualKeyCode::NumpadSubtract => WinitVirtualKeyCode::NumpadSubtract,

      RibirVirtualKeyCode::AbntC1 => WinitVirtualKeyCode::AbntC1,
      RibirVirtualKeyCode::AbntC2 => WinitVirtualKeyCode::AbntC2,
      RibirVirtualKeyCode::Apostrophe => WinitVirtualKeyCode::Apostrophe,
      RibirVirtualKeyCode::Apps => WinitVirtualKeyCode::Apps,
      RibirVirtualKeyCode::Asterisk => WinitVirtualKeyCode::Asterisk,
      RibirVirtualKeyCode::At => WinitVirtualKeyCode::At,
      RibirVirtualKeyCode::Ax => WinitVirtualKeyCode::Ax,
      RibirVirtualKeyCode::Backslash => WinitVirtualKeyCode::Backslash,
      RibirVirtualKeyCode::Calculator => WinitVirtualKeyCode::Calculator,
      RibirVirtualKeyCode::Capital => WinitVirtualKeyCode::Capital,
      RibirVirtualKeyCode::Colon => WinitVirtualKeyCode::Colon,
      RibirVirtualKeyCode::Comma => WinitVirtualKeyCode::Comma,
      RibirVirtualKeyCode::Convert => WinitVirtualKeyCode::Convert,
      RibirVirtualKeyCode::Equals => WinitVirtualKeyCode::Equals,
      RibirVirtualKeyCode::Grave => WinitVirtualKeyCode::Grave,
      RibirVirtualKeyCode::Kana => WinitVirtualKeyCode::Kana,
      RibirVirtualKeyCode::Kanji => WinitVirtualKeyCode::Kanji,
      RibirVirtualKeyCode::LAlt => WinitVirtualKeyCode::LAlt,
      RibirVirtualKeyCode::LBracket => WinitVirtualKeyCode::LBracket,
      RibirVirtualKeyCode::LControl => WinitVirtualKeyCode::LControl,
      RibirVirtualKeyCode::LShift => WinitVirtualKeyCode::LShift,
      RibirVirtualKeyCode::LWin => WinitVirtualKeyCode::LWin,
      RibirVirtualKeyCode::Mail => WinitVirtualKeyCode::Mail,
      RibirVirtualKeyCode::MediaSelect => WinitVirtualKeyCode::MediaSelect,
      RibirVirtualKeyCode::MediaStop => WinitVirtualKeyCode::MediaStop,
      RibirVirtualKeyCode::Minus => WinitVirtualKeyCode::Minus,
      RibirVirtualKeyCode::Mute => WinitVirtualKeyCode::Mute,
      RibirVirtualKeyCode::MyComputer => WinitVirtualKeyCode::MyComputer,
      RibirVirtualKeyCode::NavigateForward => WinitVirtualKeyCode::NavigateForward,
      RibirVirtualKeyCode::NavigateBackward => WinitVirtualKeyCode::NavigateBackward,
      RibirVirtualKeyCode::NextTrack => WinitVirtualKeyCode::NextTrack,
      RibirVirtualKeyCode::NoConvert => WinitVirtualKeyCode::NoConvert,
      RibirVirtualKeyCode::OEM102 => WinitVirtualKeyCode::OEM102,
      RibirVirtualKeyCode::Period => WinitVirtualKeyCode::Period,
      RibirVirtualKeyCode::PlayPause => WinitVirtualKeyCode::PlayPause,
      RibirVirtualKeyCode::Plus => WinitVirtualKeyCode::Plus,
      RibirVirtualKeyCode::Power => WinitVirtualKeyCode::Power,
      RibirVirtualKeyCode::PrevTrack => WinitVirtualKeyCode::PrevTrack,
      RibirVirtualKeyCode::RAlt => WinitVirtualKeyCode::RAlt,
      RibirVirtualKeyCode::RBracket => WinitVirtualKeyCode::RBracket,
      RibirVirtualKeyCode::RControl => WinitVirtualKeyCode::RControl,
      RibirVirtualKeyCode::RShift => WinitVirtualKeyCode::RShift,
      RibirVirtualKeyCode::RWin => WinitVirtualKeyCode::RWin,
      RibirVirtualKeyCode::Semicolon => WinitVirtualKeyCode::Semicolon,
      RibirVirtualKeyCode::Slash => WinitVirtualKeyCode::Slash,
      RibirVirtualKeyCode::Sleep => WinitVirtualKeyCode::Sleep,
      RibirVirtualKeyCode::Stop => WinitVirtualKeyCode::Stop,
      RibirVirtualKeyCode::Sysrq => WinitVirtualKeyCode::Sysrq,
      RibirVirtualKeyCode::Tab => WinitVirtualKeyCode::Tab,
      RibirVirtualKeyCode::Underline => WinitVirtualKeyCode::Underline,
      RibirVirtualKeyCode::Unlabeled => WinitVirtualKeyCode::Unlabeled,
      RibirVirtualKeyCode::VolumeDown => WinitVirtualKeyCode::VolumeDown,
      RibirVirtualKeyCode::VolumeUp => WinitVirtualKeyCode::VolumeUp,
      RibirVirtualKeyCode::Wake => WinitVirtualKeyCode::Wake,
      RibirVirtualKeyCode::WebBack => WinitVirtualKeyCode::WebBack,
      RibirVirtualKeyCode::WebFavorites => WinitVirtualKeyCode::WebFavorites,
      RibirVirtualKeyCode::WebForward => WinitVirtualKeyCode::WebForward,
      RibirVirtualKeyCode::WebHome => WinitVirtualKeyCode::WebHome,
      RibirVirtualKeyCode::WebRefresh => WinitVirtualKeyCode::WebRefresh,
      RibirVirtualKeyCode::WebSearch => WinitVirtualKeyCode::WebSearch,
      RibirVirtualKeyCode::WebStop => WinitVirtualKeyCode::WebStop,
      RibirVirtualKeyCode::Yen => WinitVirtualKeyCode::Yen,
      RibirVirtualKeyCode::Copy => WinitVirtualKeyCode::Copy,
      RibirVirtualKeyCode::Paste => WinitVirtualKeyCode::Paste,
      RibirVirtualKeyCode::Cut => WinitVirtualKeyCode::Cut,
    };
    kc.into()
  }
}
