#version 450
layout(local_size_x = 1) in;

layout(set = 0, binding = 0) buffer PrimeIndices {
    uint[] indices;
};

void main() {
    
    uint index = gl_GlobalInvocationID.x;
    uint bgra = indices[index];

    // bgra to rgba in little-endian.
    uint rgba =  
      ((bgra << 16) & 0x00FF0000u) |
      ((bgra >> 16) & 0x000000FFu) |
      (bgra & 0xFF00FF00u);

     indices[index] = rgba;
}