name: CHANGELOG
on:
  merge_group:
  pull_request_target:
    types: [labeled, auto_merge_enabled]
    branches:
      - master
      - release-*

jobs:
  update-pr-number:
    if: ${{ github.event_name != 'labeled' || github.event.label.name == 'B-merge-ready' }}
    runs-on: ubuntu-latest
    env:
      HAS_APPROVAL: "false"
      CHANGELOG_UPDATED: "false"
  
    permissions:
      contents: write
      pull-requests: write

    steps:
      # Verify PR readiness (approvals)
      - name: Verify PR Readiness
        if: ${{ github.event_name != 'merge_group' }}
        id: verify-pr-readiness
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const { data: reviews } = await github.rest.pulls.listReviews({
              owner,
              repo,
              pull_number: context.payload.pull_request.number,
              per_page: 100
            });
            
            const hasApproval = reviews.some(review => review.state === 'APPROVED');
            core.exportVariable('HAS_APPROVAL', hasApproval.toString());

      # Checkout PR branch if ready
      - name: Checkout PR Branch
        if: ${{ env.HAS_APPROVAL == 'true' }}
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          fetch-depth: 0

      # Configure Git user details once
      - name: Configure Git User
        if: ${{ env.HAS_APPROVAL == 'true' }}
        run: |
          git config user.name "RChangelog[bot]"
          git config user.email "155627257+RChangelog[bot]@users.noreply.github.com"

      # Update PR number in CHANGELOG.md
      - name: Update Changelog
        if: ${{ env.HAS_APPROVAL == 'true' }}
        shell: bash
        run: |
          # Replace placeholder with PR number in CHANGELOG.md
          sed -i '/^##/,$ {s/#pr/#${{ github.event.pull_request.number }}/g}' ./CHANGELOG.md
          
          # Check if changelog was modified and set output accordingly
          if git diff --exit-code --quiet CHANGELOG.md; then
            echo "CHANGELOG_UPDATED=false" >> $GITHUB_ENV
          else
            echo "CHANGELOG_UPDATED=true" >> $GITHUB_ENV
            git add CHANGELOG.md && git commit --amend --no-edit && git push -f
          fi
      - run: sleep 3s

      # Auto-approve the PR
      - name: Auto-Approve PR
        if: ${{ env.HAS_APPROVAL == 'true' && env.CHANGELOG_UPDATED == 'true' }}
        uses: hmarr/auto-approve-action@v4
        with:
          review-message: "Auto-approved: Changelog updated with PR number."

      # Manage labels
      - name: Manage Labels
        if: ${{ github.event_name != 'merge_group' }}
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.RIBIR_RELEASE }}
          script: |
            const { owner, repo } = context.repo;
            const issue_number = context.payload.pull_request.number;

            const hasApproved = process.env.HAS_APPROVAL === 'true';
            const changelogUpdated = process.env.CHANGELOG_UPDATED === 'true';

            async function removeLabel(labelName) {
              try { await github.rest.issues.removeLabel({ owner, repo, issue_number, name: labelName }); } catch (error) {} // Ignore errors if label doesn't exist
            }
            
            // Maintain workflow integrity by removing B-merge-ready label:
            // - Unapproved: Reset state for subsequent attempts
            // - Approved: Prevent cyclic execution post-completion
            await removeLabel('B-merge-ready');

            if (!hasApproved) {
              throw new Error("PR is not approved");
            }

            if (changelogUpdated) {
              await github.rest.issues.addLabels({ owner, repo, issue_number, labels: ['B-pr-num'] });
            }