name: Update CHANGELOG on PR Approval
permissions:
  contents: write
  pull-requests: write
on:
  pull_request_review:
    types: [submitted]
jobs:
  update-changelog:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for checkout and push
      pull-requests: write
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          fetch-depth: 0

      - name: Update PR number in CHANGELOG
        shell: bash
        run: |
          sed -i '/^##/,$ {s/#pr/#${{ github.event.pull_request.number }}/g}' ./CHANGELOG.md
          if [ $(git status --porcelain | wc -l) -eq 0 ]; then
            echo "No changes to commit."
            exit 0
          fi

          # Configure Git
          git config user.name "RChangelog[bot]"
          git config user.email "155627257+RChangelog[bot]@users.noreply.github.com"

          # Commit and push changes
          git add CHANGELOG.md
          git commit --amend --no-edit
          git push -f
      # Wait 3 seconds before adding label to trigger push event
      - run: sleep 3s
      - uses: hmarr/auto-approve-action@v4
        if: github.event.review.state != 'approved'
        with:
          review-message: "An auto approved after bot, because ${{ github.actor }} already approved before."
    
