name: CHANGELOG
on:
  merge_group:
  pull_request_target:
    types: [labeled, auto_merge_enabled]
    branches:
      - master
      - release-*

jobs:
  update-pr-number:
    if: ${{ github.event_name != 'labeled' || github.event.label.name == 'B-merge-ready' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required for checkout and push
      pull-requests: write

    steps:
      # Verify PR readiness (approvals)
      - name: Verify PR Readiness
        if: ${{ github.event_name != 'merge_group' }}
        id: verify-pr-readiness
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const { data: reviews } = await github.rest.pulls.listReviews({
              owner,
              repo,
              pull_number: context.payload.pull_request.number,
              per_page: 100
            });
            const hasApproval = reviews.some(review => review.state === 'APPROVED');
            core.setOutput('has_approval', hasApproval);

      # Checkout PR branch if ready
      - name: Checkout PR Branch
        if: ${{ steps.verify-pr-readiness.outputs.has_approval == 'true' }}
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          fetch-depth: 0

      # Configure Git user details once
      - name: Configure Git User
        if: ${{ steps.verify-pr-readiness.outputs.has_approval == 'true' }}
        run: |
          git config user.name "RChangelog[bot]"
          git config user.email "155627257+RChangelog[bot]@users.noreply.github.com"

      # Update PR number in CHANGELOG.md and commit changes if necessary
      - name: Update Changelog
        if: ${{ steps.verify-pr-readiness.outputs.has_approval == 'true' }}
        shell: bash
        run: |
          # Replace placeholder with PR number in CHANGELOG.md
          sed -i '/^##/,$ {s/#pr/#${{ github.event.pull_request.number }}/g}' ./CHANGELOG.md
          
          # Check if changelog was modified and set output accordingly
          if git diff --exit-code --quiet CHANGELOG.md; then
            echo "changelog_updated=false" >> $GITHUB_OUTPUT
          else
            echo "changelog_updated=true" >> $GITHUB_OUTPUT
            git add CHANGELOG.md && git commit --amend --no-edit && git push -f
          fi
      - run: sleep 3s
      # Auto-approve the PR after successful updates (if applicable)
      - name : Auto-Approve PR 
        if : ${{ steps.verify-pr-readiness.outputs.has_approval == 'true' && steps.update-changelog.outputs.changelog_updated == 'true' }}
        uses : hmarr/auto-approve-action@v4 
        with :
          review-message : "Auto-approved again because only update the PR number."  

      # Manage labels based on PR readiness and changelog updates  
      - name : Manage Labels
        if: ${{ github.event_name != 'merge_group' }}
        uses : actions/github-script@v7
        with :
          github-token: ${{ secrets.RIBIR_RELEASE }}
          script: |
            const { owner, repo } = context.repo;
            const issue_number = context.payload.pull_request.number;
          
            const isReady = ${{ steps.verify-pr-readiness.outputs.has_approval == 'true' }};
            const changelogUpdated = ${{ steps.update-changelog.outputs.changelog_updated == 'true'}};

            async function removeLabel(labelName) {
              try { await github.rest.issues.removeLabel({ owner, repo, issue_number, name: labelName }); } catch (error) {} // Ignore errors if label doesn't exist
            }

            if (isReady && changelogUpdated) {   
              await removeLabel('B-pr-num');
              await github.rest.issues.addLabels({ owner , repo , issue_number , labels:['B-pr-num'] });
              console.log("Added 'B-pr-num' label");   
            } else {   
              await removeLabel('B-merge-ready');   
              throw new Error("PR is not ready"); // Exit workflow early when conditions aren't met    
            }
